spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/goproducts
    username: root
    password: toor
  jpa:
    show-sql: true
    hibernate:
      properties:
        format_sql: true
      ddl-auto: update
logging:
  level:
    com:
      positivoempreendimentos:
        backoffice: DEBUG